import { StyleSheet, Platform } from 'react-native';
import { colors, radii, spacing, typography } from '../../constants/theme';

export const styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(26, 24, 22, 0.75)',
    justifyContent: 'flex-end',
  },
  sheetContainer: {
    height: '92%',
    backgroundColor: colors.bgSurfaceRaised,
    borderTopLeftRadius: radii.sheet,
    borderTopRightRadius: radii.sheet,
    borderTopWidth: 1,
    borderColor: colors.borderHairline,
    shadowOpacity: 0,
    elevation: 0,
    overflow: 'hidden',
  },
  handleContainer: {
    alignItems: 'center',
    paddingTop: spacing.sm,
    paddingBottom: spacing.xs,
  },
  handle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.borderHairline,
  },
  navBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.sm,
    paddingBottom: spacing.sm,
    gap: spacing.xs,
  },
  navBarButton: {
    minWidth: 76,
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.xs,
    justifyContent: 'center',
  },
  navBarButtonWide: {
    minWidth: 96,
  },
  navBarButtonText: {
    fontSize: 15,
    color: colors.textSecondary,
    fontWeight: '500',
  },
  navBarButtonTextRight: {
    textAlign: 'right',
  },
  navBarTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 17,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  divider: {
    height: 1,
    backgroundColor: colors.borderHairline,
  },
  bodyContainer: {
    flex: 1,
  },
  stepContainer: {
    flex: 1,
  },
  filterSection: {
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
    paddingBottom: spacing.sm,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.bgSurface,
    borderRadius: radii.controls,
    borderWidth: 1,
    borderColor: colors.borderHairline,
    paddingHorizontal: spacing.sm,
    height: 44,
  },
  searchInput: {
    flex: 1,
    height: '100%',
    color: colors.textPrimary,
    fontSize: 16,
    lineHeight: 20,
    paddingVertical: 0,
    textAlignVertical: 'center',
    includeFontPadding: false,
  },
  searchClearButton: {
    paddingVertical: spacing.xs,
    paddingLeft: spacing.sm,
  },
  searchClearText: {
    color: colors.textSecondary,
    fontSize: 14,
    fontWeight: '500',
  },
  suggestionBar: {
    marginTop: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    backgroundColor: colors.bgSurface,
    borderRadius: radii.controls,
    borderWidth: 1,
    borderColor: colors.accentKeyIdea,
    paddingLeft: spacing.sm,
    paddingRight: spacing.xs,
    paddingVertical: spacing.xs,
  },
  suggestionLabel: {
    flex: 1,
    fontFamily: typography.body.fontFamily,
    fontSize: 16,
    lineHeight: 22,
    color: colors.textPrimary,
  },
  suggestionAdd: {
    paddingVertical: 8,
    paddingHorizontal: spacing.sm,
    borderRadius: radii.controls,
    backgroundColor: colors.accentKeyIdea,
  },
  suggestionAddText: {
    color: colors.bgBase,
    fontSize: 14,
    fontWeight: '600',
  },
  bookListContent: {
    paddingBottom: spacing.lg,
  },
  sectionLabel: {
    ...typography.label,
    color: colors.textSecondary,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.md,
    paddingBottom: spacing.xs,
  },
  bookRow: {
    minHeight: 48,
    paddingHorizontal: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: colors.borderHairline,
  },
  bookRowExpanded: {
    backgroundColor: colors.bgSurface,
    borderBottomWidth: 0,
  },
  bookRowPressed: {
    backgroundColor: colors.bgSurface,
  },
  bookRowTitle: {
    flex: 1,
    fontSize: 16,
    fontWeight: '500',
    color: colors.textPrimary,
  },
  bookRowTitleExpanded: {
    color: colors.accentKeyIdea,
    fontWeight: '600',
  },
  disclosure: {
    marginLeft: spacing.sm,
  },
  chapterWell: {
    backgroundColor: colors.bgSurface,
    paddingHorizontal: spacing.md,
    paddingBottom: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderHairline,
  },
  gridContainer: {
    padding: spacing.md,
    paddingBottom: spacing.xl,
  },
  chapterGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
  },
  chapterTile: {
    backgroundColor: colors.bgSurfaceRaised,
    borderRadius: radii.controls,
    borderWidth: 1,
    borderColor: colors.borderHairline,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chapterTileSelected: {
    borderColor: colors.accentKeyIdea,
    backgroundColor: colors.bgSurfaceRaised,
  },
  chapterTileText: {
    fontSize: 15,
    lineHeight: 18,
    fontWeight: '600',
    color: colors.textPrimary,
    textAlign: 'center',
    fontVariant: ['tabular-nums'],
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  chapterTileTextSelected: {
    color: colors.accentKeyIdea,
  },
  verseActionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.md,
    paddingBottom: spacing.xs,
  },
  verseHint: {
    ...typography.label,
    color: colors.textSecondary,
    paddingHorizontal: spacing.md,
    paddingBottom: spacing.sm,
  },
  wholeChapterChip: {
    backgroundColor: colors.bgSurface,
    borderRadius: radii.controls,
    borderWidth: 1,
    borderColor: colors.borderHairline,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  wholeChapterChipText: {
    fontSize: 14,
    color: colors.accentKeyIdea,
    fontWeight: '500',
  },
  verseGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
  },
  verseTile: {
    backgroundColor: colors.bgSurface,
    borderRadius: radii.controls,
    borderWidth: 1,
    borderColor: colors.borderHairline,
    alignItems: 'center',
    justifyContent: 'center',
  },
  verseTileInRange: {
    backgroundColor: 'rgba(227, 165, 61, 0.15)',
    borderColor: colors.accentKeyIdea,
  },
  verseTileEndpoint: {
    backgroundColor: colors.accentKeyIdea,
    borderColor: colors.accentKeyIdea,
  },
  verseTileText: {
    fontSize: 15,
    lineHeight: 18,
    fontWeight: '500',
    color: colors.textPrimary,
    textAlign: 'center',
    fontVariant: ['tabular-nums'],
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  verseTileTextInRange: {
    color: colors.accentKeyIdea,
    fontWeight: '600',
  },
  verseTileTextEndpoint: {
    color: colors.bgBase,
    fontWeight: '700',
  },
  emptyFilter: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.lg,
  },
  emptyFilterText: {
    fontSize: 16,
    lineHeight: 22,
    color: colors.textSecondary,
  },
  footerContainer: {
    backgroundColor: colors.bgSurface,
    borderTopWidth: 1,
    borderColor: colors.borderHairline,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
    paddingBottom: Platform.OS === 'ios' ? spacing.lg : spacing.md,
    gap: spacing.sm,
  },
  hintText: {
    ...typography.label,
    color: colors.textSecondary,
  },
  passagesHeading: {
    ...typography.label,
    color: colors.textSecondary,
  },
  passageList: {
    maxHeight: 176,
  },
  passageListContent: {
    gap: spacing.sm,
    paddingBottom: spacing.xs,
  },
  passageRow: {
    backgroundColor: colors.bgSurfaceRaised,
    borderRadius: radii.content,
    borderWidth: 1,
    borderColor: colors.borderHairline,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    gap: spacing.xs,
  },
  passageRowEditing: {
    borderColor: colors.accentKeyIdea,
  },
  passageReference: {
    fontFamily: typography.body.fontFamily,
    fontSize: 16,
    lineHeight: 22,
    color: colors.textPrimary,
  },
  editingCaption: {
    ...typography.caption,
    color: colors.accentKeyIdea,
  },
  passageActions: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: spacing.xs,
  },
  textAction: {
    paddingVertical: 6,
    paddingHorizontal: spacing.sm,
    borderRadius: radii.controls,
    backgroundColor: colors.bgSurface,
    borderWidth: 1,
    borderColor: colors.borderHairline,
  },
  textActionDisabled: {
    opacity: 0.4,
  },
  textActionLabel: {
    fontSize: 14,
    fontWeight: '500',
    color: colors.textPrimary,
  },
  textActionDanger: {
    color: colors.accentDanger,
  },
  draftBlock: {
    gap: 2,
  },
  summaryLabel: {
    ...typography.caption,
    color: colors.textSecondary,
  },
  draftReference: {
    fontFamily: typography.body.fontFamily,
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  actionButtonGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  addSegmentButton: {
    flex: 1,
    backgroundColor: colors.bgSurfaceRaised,
    borderWidth: 1,
    borderColor: colors.borderHairline,
    borderRadius: radii.controls,
    paddingVertical: 12,
    paddingHorizontal: spacing.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addSegmentButtonText: {
    color: colors.accentKeyIdea,
    fontSize: 15,
    fontWeight: '600',
  },
  confirmButton: {
    flex: 1,
    backgroundColor: colors.accentKeyIdea,
    borderRadius: radii.controls,
    paddingVertical: 12,
    paddingHorizontal: spacing.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  confirmButtonText: {
    color: colors.bgBase,
    fontSize: 15,
    fontWeight: '600',
  },
  buttonDisabled: {
    opacity: 0.4,
  },
});
