import { StyleSheet, Platform } from 'react-native';
import { colors, radii, spacing } from '../../constants/theme';

export const styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(26, 24, 22, 0.75)',
    justifyContent: 'flex-end',
  },
  sheetContainer: {
    height: '88%',
    backgroundColor: colors.bgSurfaceRaised,
    borderTopLeftRadius: radii.sheet,
    borderTopRightRadius: radii.sheet,
    borderTopWidth: 1,
    borderColor: colors.borderHairline,
    shadowOpacity: 0,
    elevation: 0,
    overflow: 'hidden',
  },
  handleContainer: {
    alignItems: 'center',
    paddingVertical: spacing.sm,
  },
  handle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.borderHairline,
  },
  navBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.md,
    paddingBottom: spacing.sm,
  },
  navBarButton: {
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.xs,
    minWidth: 50,
  },
  navBarButtonText: {
    fontSize: 15,
    color: colors.textSecondary,
    fontWeight: '500',
  },
  navBarTitle: {
    fontSize: 17,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  navBarResetText: {
    fontSize: 14,
    color: colors.textSecondary,
    textAlign: 'right',
  },
  breadcrumbBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    gap: spacing.xs,
  },
  breadcrumbChip: {
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: radii.controls,
    backgroundColor: colors.bgSurface,
    borderWidth: 1,
    borderColor: colors.borderHairline,
  },
  breadcrumbChipActive: {
    borderColor: colors.accentKeyIdea,
    backgroundColor: colors.bgSurfaceRaised,
  },
  breadcrumbText: {
    fontSize: 13,
    color: colors.textSecondary,
    fontWeight: '500',
  },
  breadcrumbTextActive: {
    color: colors.accentKeyIdea,
    fontWeight: '600',
  },
  breadcrumbSeparator: {
    fontSize: 14,
    color: colors.textDisabled,
  },
  divider: {
    height: 1,
    backgroundColor: colors.borderHairline,
    marginTop: spacing.xs,
  },
  bodyContainer: {
    flex: 1,
  },
  stepContainer: {
    flex: 1,
  },
  filterSection: {
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
    paddingBottom: spacing.xs,
  },
  segmentContainer: {
    flexDirection: 'row',
    backgroundColor: colors.bgSurface,
    borderRadius: radii.controls,
    padding: 3,
    borderWidth: 1,
    borderColor: colors.borderHairline,
    marginBottom: spacing.sm,
  },
  segmentButton: {
    flex: 1,
    paddingVertical: 8,
    alignItems: 'center',
    borderRadius: 6,
  },
  segmentButtonActive: {
    backgroundColor: colors.bgSurfaceRaised,
    borderColor: colors.accentKeyIdea,
  },
  segmentText: {
    fontSize: 13,
    fontWeight: '500',
    color: colors.textSecondary,
  },
  segmentTextActive: {
    color: colors.textPrimary,
    fontWeight: '600',
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.bgSurface,
    borderRadius: radii.controls,
    borderWidth: 1,
    borderColor: colors.borderHairline,
    paddingHorizontal: spacing.sm,
    height: 38,
  },
  searchInput: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: 14,
    paddingVertical: 0,
  },
  searchClearButton: {
    padding: spacing.xs,
  },
  searchClearText: {
    color: colors.textSecondary,
    fontSize: 12,
  },
  gridContainer: {
    padding: spacing.md,
    paddingBottom: spacing.xxl,
  },
  bookGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  bookTile: {
    width: '31%',
    backgroundColor: colors.bgSurface,
    borderRadius: radii.controls,
    borderWidth: 1,
    borderColor: colors.borderHairline,
    paddingVertical: 12,
    paddingHorizontal: 4,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 64,
  },
  bookTileSelected: {
    borderColor: colors.accentKeyIdea,
    backgroundColor: colors.bgSurfaceRaised,
  },
  bookTileTitle: {
    fontSize: 13,
    fontWeight: '500',
    color: colors.textPrimary,
    textAlign: 'center',
    marginBottom: 2,
  },
  bookTileTitleSelected: {
    color: colors.accentKeyIdea,
    fontWeight: '600',
  },
  bookTileSubtitle: {
    fontSize: 11,
    color: colors.textSecondary,
  },
  stepHeaderNotice: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  stepHeaderNoticeText: {
    fontSize: 13,
    color: colors.textSecondary,
  },
  chapterGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  chapterTile: {
    backgroundColor: colors.bgSurface,
    borderRadius: radii.controls,
    borderWidth: 1,
    borderColor: colors.borderHairline,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
  },
  chapterTileSelected: {
    borderColor: colors.accentKeyIdea,
    backgroundColor: colors.bgSurfaceRaised,
  },
  chapterTileText: {
    fontSize: 15,
    lineHeight: 18,
    fontWeight: '600',
    color: colors.textPrimary,
    textAlign: 'center',
    fontVariant: ['tabular-nums'],
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  chapterTileTextSelected: {
    color: colors.accentKeyIdea,
  },
  verseActionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  wholeChapterChip: {
    backgroundColor: colors.bgSurface,
    borderRadius: radii.controls,
    borderWidth: 1,
    borderColor: colors.borderHairline,
    paddingVertical: 5,
    paddingHorizontal: 10,
  },
  wholeChapterChipText: {
    fontSize: 12,
    color: colors.accentKeyIdea,
    fontWeight: '500',
  },
  verseGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  verseTile: {
    backgroundColor: colors.bgSurface,
    borderRadius: radii.controls,
    borderWidth: 1,
    borderColor: colors.borderHairline,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
  },
  verseTileInRange: {
    backgroundColor: 'rgba(227, 165, 61, 0.15)',
    borderColor: colors.accentKeyIdea,
    borderWidth: 1,
  },
  verseTileEndpoint: {
    backgroundColor: colors.accentKeyIdea,
    borderColor: colors.accentKeyIdea,
  },
  verseTileText: {
    fontSize: 15,
    lineHeight: 18,
    fontWeight: '500',
    color: colors.textPrimary,
    textAlign: 'center',
    fontVariant: ['tabular-nums'],
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  verseTileTextInRange: {
    color: colors.accentKeyIdea,
    fontWeight: '600',
    textAlign: 'center',
    lineHeight: 18,
    includeFontPadding: false,
  },
  verseTileTextEndpoint: {
    color: colors.bgBase,
    fontWeight: '700',
    textAlign: 'center',
    lineHeight: 18,
    includeFontPadding: false,
  },
  footerContainer: {
    backgroundColor: colors.bgSurface,
    borderTopWidth: 1,
    borderColor: colors.borderHairline,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
    paddingBottom: Platform.OS === 'ios' ? spacing.lg : spacing.md,
  },
  summaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  summaryTextColumn: {
    flex: 1,
    marginRight: spacing.md,
  },
  summaryLabel: {
    fontSize: 11,
    color: colors.textSecondary,
    marginBottom: 2,
  },
  summaryReference: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  stagedSegmentsContainer: {
    paddingBottom: spacing.sm,
    borderBottomWidth: 1,
    borderColor: colors.borderHairline,
    marginBottom: spacing.xs,
  },
  stagedSegmentsList: {
    gap: spacing.xs,
    alignItems: 'center',
  },
  stagedSegmentChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.bgSurfaceRaised,
    borderRadius: radii.controls,
    borderWidth: 1,
    borderColor: colors.borderHairline,
    paddingVertical: 4,
    paddingHorizontal: 8,
    gap: 6,
  },
  stagedSegmentText: {
    fontSize: 12,
    color: colors.textPrimary,
    fontWeight: '500',
  },
  removeSegmentButton: {
    padding: 2,
  },
  removeSegmentIcon: {
    fontSize: 11,
    color: colors.textDisabled,
    fontWeight: '700',
  },
  chapterTileInRange: {
    backgroundColor: 'rgba(227, 165, 61, 0.15)',
    borderColor: colors.accentKeyIdea,
  },
  chapterTileTextInRange: {
    color: colors.accentKeyIdea,
  },
  actionButtonGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  addSegmentButton: {
    backgroundColor: colors.bgSurfaceRaised,
    borderWidth: 1,
    borderColor: colors.borderHairline,
    borderRadius: radii.controls,
    paddingVertical: 10,
    paddingHorizontal: spacing.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addSegmentButtonText: {
    color: colors.accentKeyIdea,
    fontSize: 14,
    fontWeight: '600',
  },
  confirmButton: {
    backgroundColor: colors.accentKeyIdea,
    borderRadius: radii.controls,
    paddingVertical: 10,
    paddingHorizontal: spacing.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  confirmButtonText: {
    color: colors.bgBase,
    fontSize: 14,
    fontWeight: '600',
  },
});
