/**
 * Auto-generated by scripts/buildCrossReferences.js — do not edit by hand.
 * Cross-reference data © OpenBible.info, CC BY 4.0
 * https://www.openbible.info/labs/cross-references/
 */

export type CrossRefTuple = [
  bookIndex: number,
  startChapter: number,
  startVerse: number,
  endChapter: number,
  endVerse: number,
  votes: number,
];

export type CrossRefBookData = Record<string, Record<string, CrossRefTuple[]>>;

const loaders: Record<number, () => CrossRefBookData> = {
  0: () => require('./0.json') as CrossRefBookData,
  1: () => require('./1.json') as CrossRefBookData,
  2: () => require('./2.json') as CrossRefBookData,
  3: () => require('./3.json') as CrossRefBookData,
  4: () => require('./4.json') as CrossRefBookData,
  5: () => require('./5.json') as CrossRefBookData,
  6: () => require('./6.json') as CrossRefBookData,
  7: () => require('./7.json') as CrossRefBookData,
  8: () => require('./8.json') as CrossRefBookData,
  9: () => require('./9.json') as CrossRefBookData,
  10: () => require('./10.json') as CrossRefBookData,
  11: () => require('./11.json') as CrossRefBookData,
  12: () => require('./12.json') as CrossRefBookData,
  13: () => require('./13.json') as CrossRefBookData,
  14: () => require('./14.json') as CrossRefBookData,
  15: () => require('./15.json') as CrossRefBookData,
  16: () => require('./16.json') as CrossRefBookData,
  17: () => require('./17.json') as CrossRefBookData,
  18: () => require('./18.json') as CrossRefBookData,
  19: () => require('./19.json') as CrossRefBookData,
  20: () => require('./20.json') as CrossRefBookData,
  21: () => require('./21.json') as CrossRefBookData,
  22: () => require('./22.json') as CrossRefBookData,
  23: () => require('./23.json') as CrossRefBookData,
  24: () => require('./24.json') as CrossRefBookData,
  25: () => require('./25.json') as CrossRefBookData,
  26: () => require('./26.json') as CrossRefBookData,
  27: () => require('./27.json') as CrossRefBookData,
  28: () => require('./28.json') as CrossRefBookData,
  29: () => require('./29.json') as CrossRefBookData,
  30: () => require('./30.json') as CrossRefBookData,
  31: () => require('./31.json') as CrossRefBookData,
  32: () => require('./32.json') as CrossRefBookData,
  33: () => require('./33.json') as CrossRefBookData,
  34: () => require('./34.json') as CrossRefBookData,
  35: () => require('./35.json') as CrossRefBookData,
  36: () => require('./36.json') as CrossRefBookData,
  37: () => require('./37.json') as CrossRefBookData,
  38: () => require('./38.json') as CrossRefBookData,
  39: () => require('./39.json') as CrossRefBookData,
  40: () => require('./40.json') as CrossRefBookData,
  41: () => require('./41.json') as CrossRefBookData,
  42: () => require('./42.json') as CrossRefBookData,
  43: () => require('./43.json') as CrossRefBookData,
  44: () => require('./44.json') as CrossRefBookData,
  45: () => require('./45.json') as CrossRefBookData,
  46: () => require('./46.json') as CrossRefBookData,
  47: () => require('./47.json') as CrossRefBookData,
  48: () => require('./48.json') as CrossRefBookData,
  49: () => require('./49.json') as CrossRefBookData,
  50: () => require('./50.json') as CrossRefBookData,
  51: () => require('./51.json') as CrossRefBookData,
  52: () => require('./52.json') as CrossRefBookData,
  53: () => require('./53.json') as CrossRefBookData,
  54: () => require('./54.json') as CrossRefBookData,
  55: () => require('./55.json') as CrossRefBookData,
  56: () => require('./56.json') as CrossRefBookData,
  57: () => require('./57.json') as CrossRefBookData,
  58: () => require('./58.json') as CrossRefBookData,
  59: () => require('./59.json') as CrossRefBookData,
  60: () => require('./60.json') as CrossRefBookData,
  61: () => require('./61.json') as CrossRefBookData,
  62: () => require('./62.json') as CrossRefBookData,
  63: () => require('./63.json') as CrossRefBookData,
  64: () => require('./64.json') as CrossRefBookData,
  65: () => require('./65.json') as CrossRefBookData,
};

export function loadCrossRefBook(bookIndex: number): CrossRefBookData | null {
  const loader = loaders[bookIndex];
  if (!loader) return null;
  return loader();
}

export const CROSSREF_ATTRIBUTION =
  'Cross references from OpenBible.info (CC BY 4.0)';

export const CROSSREF_BOOK_COUNT = 66;
